# Generated by Django 5.0.7 on 2024-07-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nauczyciel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('room_number', models.IntegerField()),
            ],
        ),
    ]
